# Generated by Django 4.2.29 on 2026-03-27 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('admin', 'Admin'), ('executive', 'Executive'), ('internal', 'Internal Member'), ('external', 'External Member'), ('user', 'User')], default='user', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('exec_approver', 'Executive Approver'), ('executive', 'Executive'), ('writer', 'Writer'), ('reviewer', 'Reviewer'), ('sme', 'SME'), ('none', 'None')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='RBAC',
            fields=[
                ('rbac_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('application_name', models.CharField(default='platform', max_length=50)),
                ('application_area', models.CharField(choices=[('content', 'Content Management'), ('reports', 'Reports & Analytics'), ('settings', 'System Settings'), ('board', 'Kanban Board'), ('users', 'User Management')], max_length=50)),
                ('application_action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('update', 'Update'), ('delete', 'Delete'), ('admin', 'Admin'), ('feedback', 'Feedback / Vote'), ('promote', 'Promote Status')], max_length=20)),
                ('application_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_rules', to='auth.group')),
            ],
            options={
                'verbose_name': 'RBAC Rule',
                'unique_together': {('application_group', 'application_area', 'application_action')},
            },
        ),
    ]
