# Generated by Django 4.2.29 on 2026-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbac',
            name='application_action',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('update', 'Update'), ('delete', 'Delete'), ('admin', 'Admin'), ('approve', 'Approve'), ('initiate', 'Initiate form')], max_length=20),
        ),
    ]
