# Generated by Django 6.0.2 on 2026-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('writer', 'Writer'), ('approver', 'Approver'), ('associate', 'Associate'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
