# Generated by Django 6.0.2 on 2026-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbac',
            name='application_role',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('update', 'Update'), ('delete', 'Delete'), ('admin', 'Admin'), ('feedback', 'Feedback/Vote')], max_length=20),
        ),
    ]
