### Variables
@baseUrl = http://127.0.0.1:8000/api
@base2Url = http://127.0.0.1:8000/api/content
@password = Pass123!
@adminPass = AdminPassword123

# @adminEmail = admin@insight.com
# @adminPass = Pass123!

# Article ID for testing (Update after creation)

@smeToken = {{sme_login.response.body.access}}
@writerToken = {{writer_login.response.body.access}}
@execToken = {{exec_login.response.body.access}}
@adminToken = {{adminLogin.response.body.access}}
@reviewerToken = {{reviewerLogin.response.body.access}}
@articleId = 1

# ==========================================
# 1. AUTHENTICATION (Login for all roles)
# ==========================================

### Login as Admin
# @name adminLogin
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
    "email": "admin@insight.com",
    "password": "{{adminPass}}"
}

###


### Login as Executive
# @name exec_login
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
    "email": "exec@insight.com",
    "password": "{{password}}"
}

###


### Login as Writer
# @name writer_login
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
    "email": "writer@insight.com",
    "password": "{{password}}"
}

###

### Login as SME
# @name sme_login
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
    "email": "sme@insight.com",
    "password": "{{password}}"
}

###

### Login as reviwer
# @name reviewerLogin
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
    "email": "reviewer@insight.com",
    "password": "{{password}}"
}


### Variables
# @baseUrl = http://127.0.0.1:8000/api/content
# @writerToken = your_writer_jwt_here
# @smeToken = your_sme_jwt_here
# = your_reviewer_jwt_here
# @adminToken = your_admin_jwt_here
# @articleId = 1

# ==========================================
# 1. WRITER FLOW
# ==========================================

### Create a new Draft
POST {{baseUrl}}/content/articles/create/
Authorization: Bearer {{writerToken}}
Content-Type: application/json

{
    "title": "draft3",
    "content": "draft3 content"
}

### Lock the article to start editing
POST {{base2Url}}/articles/5/lock/
Authorization: Bearer {{smeToken}}
# Authorization: Bearer {{reviewerToken}}

Authorization: Bearer {{writerToken}}

### Unlock article
DELETE {{base2Url}}/articles/3/lock/
Authorization: Bearer {{writerToken}}

### Edit the article (Must hold lock)
PUT {{base2Url}}/articles/5/edit/
Authorization: Bearer {{smeToken}}
# Authorization: Bearer {{reviewerToken}} 
#Authorization: Bearer {{writerToken}}
Content-Type: application/json

{
    "content": "Edit1"
}



# ==========================================
# 2. REVIEWER FLOW (ASSIGNMENT)
# ==========================================

### Assign an SME to the article
POST {{base2Url}}/articles/5/assign-sme/
Authorization: Bearer {{reviewerToken}}
Content-Type: application/json

{
    "sme_id": 5
}

# ==========================================
# 3. SME FLOW (TECHNICAL REVIEW)
# ==========================================


#even if not onborded om the content still aproving
### SME Technical Approval (Moves to Pending Executive)
POST {{base2Url}}/articles/5/approve/
Authorization: Bearer {{execToken}}
# Authorization: Bearer {{smeToken}}

# ==========================================
# 4. ADMIN / EXECUTIVE FLOW
# ==========================================

### Admin/Exec Comment (Kicks back to Draft)
POST {{base2Url}}/articles/4/comment/
Authorization: Bearer {{reviewerToken}}
Content-Type: application/json

{
    "comment_text": "comment1"
}

### Final Admin Approval (Publish)
# (Note: Status must be 'pending_admin' for this to work)
POST {{base2Url}}/articles/4/approve/
Authorization: Bearer {{adminToken}}

# ==========================================
# 5. AUDIT & HISTORY
# ==========================================

### View Full Version History
GET {{base2Url}}/articles/4/history/
Authorization: Bearer {{adminToken}}

### View Active (Unpublished) Articles
GET {{base2Url}}/articles/active/
Authorization: Bearer {{writerToken}}

###

GET {{base2Url}}/articles/4/comments/
Authorization: Bearer {{reviewerToken}}

###
GET {{base2Url}}/articles/published/
Authorization: Bearer {{reviewerToken}}