# Generated by Django 4.2.29 on 2026-04-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='campaign_id',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='event_id',
            new_name='event',
        ),
    ]
