# Generated by Django 4.2.29 on 2026-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
