# Generated by Django 4.2.29 on 2026-04-14 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_rename_campaign_id_task_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='board_campaign_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='board_task_assigne_f77638_idx',
            old_name='board_assigned_status_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='task',
            name='last_transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_transferred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='marketing_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Optional. Set this to make the task a subtask of another task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='board.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags e.g. design,ux,launch', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(help_text='Every task must belong to a campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.campaign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional. Task can be directly under campaign or under an event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='board.event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], db_index=True, default='to_do', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='board_task_status_51c028_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='board_task_priorit_e16e80_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='board_task_due_dat_2f84e7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['campaign', 'status'], name='board_task_campaig_f32a72_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['event'], name='board_task_event_i_9848ce_idx'),
        ),
    ]
