# Generated by Django 4.2.29 on 2026-04-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='The parent comment this is a reply to (null = top-level comment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='content.contentcomment'),
        ),
    ]
