# Generated by Django 6.0.2 on 2026-02-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_articleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.articleversion'),
        ),
    ]
