# Generated by Django 4.2.29 on 2026-04-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentcomment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='draft', max_length=30),
        ),
    ]
