# Generated by Django 4.2.29 on 2026-04-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_alter_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentassignment',
            name='sme',
            field=models.ForeignKey(limit_choices_to={'role': 'sme'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
