# Generated by Django 6.0.2 on 2026-02-25 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_articlecomment_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_executive', 'Pending Executive Review'), ('pending_admin', 'Pending Admin Review'), ('published', 'Published')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['locked_by', 'status'], name='content_art_locked__bce753_idx'),
        ),
        migrations.AddIndex(
            model_name='articleassignment',
            index=models.Index(fields=['article', 'sme'], name='idx_article_sme_lookup'),
        ),
    ]
