# Generated by Django 4.2.29 on 2026-04-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentassignment_sme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='task_id',
            new_name='task',
        ),
    ]
