# Generated by Django 6.0.2 on 2026-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_status_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleversion',
            name='title',
            field=models.CharField(default='Original Title', max_length=255),
            preserve_default=False,
        ),
    ]
