# Generated by Django 6.0.2 on 2026-03-03 10:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_articleversion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
