# Generated by Django 4.2.29 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_task_id_content_task'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_campaig_8907d7_idx',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['campaign', 'status'], name='content_con_campaig_8907d7_idx'),
        ),
    ]
