# Generated by Django 4.2.29 on 2026-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_content_content_con_campaig_8907d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcomment',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='all_approved_at',
            field=models.DateTimeField(blank=True, help_text='Set when all three approvals are collected.', null=True),
        ),
    ]
