# Generated by Django 4.2.29 on 2026-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentcomment_selected_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinitiationform',
            name='initiated',
            field=models.BooleanField(default=False),
        ),
    ]
